title: Jinhui Ouyang's Homepage
page-top-title: Jinhui Ouyang
top-section-bg-text: Exploring artificial intelligence methods for ubiquitous applications.
home-subtitle: Jinhui Ouyang&ensp;|&ensp; 欧阳锦晖
copyright-text: '&copy; Jinhui Ouyang 2023-2024. All Rights Reserved.'
