title: Jinhui Ouyang's Homepage
page-top-title: Jinhui Ouyang
top-section-bg-text: Exploring opportunities for human-machine co-evolution.
home-subtitle: Jinhui Ouyang&ensp;|&ensp; 欧阳锦晖
copyright-text: '&copy; Jinhui Ouyang 2023-2024. All Rights Reserved.'
