title: Jinhui Ouyang's Homepage
page-top-title: Jinhui Ouyang
top-section-bg-text: Hi! I focus on applying human-computer interaction (HCI), artificial intelligence (AI) methods for ubiquitous applications.
home-subtitle: Jinhui Ouyang&ensp;|&ensp; 欧阳锦晖
copyright-text: '&copy; Jinhui Ouyang 2023-2024. All Rights Reserved.'
